# Dapr Secret Store Component - Kubernetes Secrets
# Phase V: Used for secure secret management across services
# SAFE MODE: New file only, no existing code modified

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kubernetes-secrets
  namespace: default
spec:
  type: secretstores.kubernetes
  version: v1
  metadata: []
# Scopes: which app IDs can access secrets
scopes:
  - todo-backend
  - notification-service
  - recurring-task-service
  - audit-service
---
# Secret Store for local development (file-based)
# Use this for local Dapr standalone mode
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: local-secrets
  namespace: default
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsFile
      value: "./secrets.json"
    - name: nestedSeparator
      value: ":"
scopes:
  - todo-backend
