openapi: 3.1.0
info:
  title: Todo API v2 - Phase V Extensions
  description: Extended Task API with recurring tasks, reminders, priorities, and tags
  version: 2.0.0
  contact:
    name: Todo App Team

servers:
  - url: http://localhost:8000/api
    description: Local development
  - url: https://todo-app.example.com/api
    description: Production

tags:
  - name: Tasks
    description: Task CRUD operations (extended)
  - name: Tags
    description: Tag management
  - name: Reminders
    description: Reminder management

paths:
  /tasks:
    get:
      tags: [Tasks]
      summary: List tasks with filtering and sorting
      description: Get all tasks for the authenticated user with optional filters
      operationId: listTasks
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [all, pending, completed]
            default: all
        - name: priority
          in: query
          schema:
            type: string
            enum: [low, medium, high]
        - name: tags
          in: query
          description: Comma-separated tag IDs
          schema:
            type: string
        - name: due_before
          in: query
          description: Filter tasks due before this date
          schema:
            type: string
            format: date-time
        - name: due_after
          in: query
          description: Filter tasks due after this date
          schema:
            type: string
            format: date-time
        - name: search
          in: query
          description: Full-text search in title and description
          schema:
            type: string
        - name: sort
          in: query
          schema:
            type: string
            enum: [created_at, due_at, priority, title]
            default: created_at
        - name: order
          in: query
          schema:
            type: string
            enum: [asc, desc]
            default: desc
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
            maximum: 100
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskListResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'

    post:
      tags: [Tasks]
      summary: Create a new task
      description: Create task with optional recurrence, due date, priority, and tags
      operationId: createTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /tasks/{task_id}:
    parameters:
      - name: task_id
        in: path
        required: true
        schema:
          type: string
          format: uuid

    get:
      tags: [Tasks]
      summary: Get task by ID
      operationId: getTask
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    patch:
      tags: [Tasks]
      summary: Update task
      operationId: updateTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      tags: [Tasks]
      summary: Delete task
      description: Deletes task and cancels any pending reminders
      operationId: deleteTask
      responses:
        '204':
          description: Task deleted
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /tasks/{task_id}/complete:
    post:
      tags: [Tasks]
      summary: Mark task as complete
      description: Marks task complete and triggers recurring task generation if applicable
      operationId: completeTask
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Task completed
          content:
            application/json:
              schema:
                type: object
                properties:
                  task:
                    $ref: '#/components/schemas/TaskResponse'
                  next_occurrence:
                    $ref: '#/components/schemas/TaskResponse'
                    nullable: true
                    description: Next recurring task instance (if recurring)
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /tasks/{task_id}/tags:
    parameters:
      - name: task_id
        in: path
        required: true
        schema:
          type: string
          format: uuid

    put:
      tags: [Tasks]
      summary: Set task tags
      description: Replace all tags on a task (max 10)
      operationId: setTaskTags
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tag_ids:
                  type: array
                  items:
                    type: string
                    format: uuid
                  maxItems: 10
      responses:
        '200':
          description: Tags updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /tasks/{task_id}/reminder:
    parameters:
      - name: task_id
        in: path
        required: true
        schema:
          type: string
          format: uuid

    post:
      tags: [Reminders]
      summary: Set task reminder
      description: Schedule a reminder for this task (replaces existing reminder)
      operationId: setReminder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [remind_at]
              properties:
                remind_at:
                  type: string
                  format: date-time
                  description: When to send the reminder
      responses:
        '200':
          description: Reminder scheduled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReminderResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      tags: [Reminders]
      summary: Cancel task reminder
      operationId: cancelReminder
      responses:
        '204':
          description: Reminder cancelled
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /tags:
    get:
      tags: [Tags]
      summary: List user tags
      operationId: listTags
      responses:
        '200':
          description: List of tags
          content:
            application/json:
              schema:
                type: object
                properties:
                  tags:
                    type: array
                    items:
                      $ref: '#/components/schemas/TagResponse'
                  total:
                    type: integer
        '401':
          $ref: '#/components/responses/Unauthorized'

    post:
      tags: [Tags]
      summary: Create a new tag
      operationId: createTag
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TagCreate'
      responses:
        '201':
          description: Tag created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '409':
          description: Tag name already exists

  /tags/{tag_id}:
    parameters:
      - name: tag_id
        in: path
        required: true
        schema:
          type: string
          format: uuid

    patch:
      tags: [Tags]
      summary: Update tag
      operationId: updateTag
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TagUpdate'
      responses:
        '200':
          description: Tag updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      tags: [Tags]
      summary: Delete tag
      description: Removes tag from all associated tasks
      operationId: deleteTag
      responses:
        '204':
          description: Tag deleted
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  schemas:
    RecurrenceType:
      type: string
      enum: [none, daily, weekly, custom]
      default: none

    Priority:
      type: string
      enum: [low, medium, high]
      default: medium

    ReminderStatus:
      type: string
      enum: [pending, sent, cancelled, failed]

    TaskCreate:
      type: object
      required: [title]
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
        description:
          type: string
          maxLength: 2000
          nullable: true
        recurrence_type:
          $ref: '#/components/schemas/RecurrenceType'
        recurrence_interval:
          type: integer
          minimum: 1
          maximum: 365
          description: Days for custom recurrence
          nullable: true
        due_at:
          type: string
          format: date-time
          nullable: true
        remind_at:
          type: string
          format: date-time
          nullable: true
          description: Convenience field to set reminder on creation
        priority:
          $ref: '#/components/schemas/Priority'
        tag_ids:
          type: array
          items:
            type: string
            format: uuid
          maxItems: 10

    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
        description:
          type: string
          maxLength: 2000
          nullable: true
        recurrence_type:
          $ref: '#/components/schemas/RecurrenceType'
        recurrence_interval:
          type: integer
          minimum: 1
          maximum: 365
          nullable: true
        due_at:
          type: string
          format: date-time
          nullable: true
        priority:
          $ref: '#/components/schemas/Priority'
        is_completed:
          type: boolean

    TaskResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
          nullable: true
        is_completed:
          type: boolean
        recurrence_type:
          $ref: '#/components/schemas/RecurrenceType'
        recurrence_interval:
          type: integer
          nullable: true
        next_occurrence_at:
          type: string
          format: date-time
          nullable: true
        due_at:
          type: string
          format: date-time
          nullable: true
        priority:
          $ref: '#/components/schemas/Priority'
        parent_task_id:
          type: string
          format: uuid
          nullable: true
        tags:
          type: array
          items:
            $ref: '#/components/schemas/TagResponse'
        reminder:
          $ref: '#/components/schemas/ReminderResponse'
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    TaskListResponse:
      type: object
      properties:
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/TaskResponse'
        total:
          type: integer
        has_more:
          type: boolean

    TagCreate:
      type: object
      required: [name]
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 50
        color:
          type: string
          pattern: '^#[0-9A-Fa-f]{6}$'
          nullable: true

    TagUpdate:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 50
        color:
          type: string
          pattern: '^#[0-9A-Fa-f]{6}$'
          nullable: true

    TagResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        color:
          type: string
          nullable: true
        created_at:
          type: string
          format: date-time

    ReminderResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        task_id:
          type: string
          format: uuid
        remind_at:
          type: string
          format: date-time
        status:
          $ref: '#/components/schemas/ReminderStatus'
        created_at:
          type: string
          format: date-time
        sent_at:
          type: string
          format: date-time
          nullable: true

    Error:
      type: object
      properties:
        detail:
          type: string
        code:
          type: string

  responses:
    BadRequest:
      description: Invalid request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Authentication required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []
